### ISSUE TITLE
How do i create Test definition file nist?

### ISSUE THREAD

**Issue by dheeraj-thedev** [stamfest/randomtests#2]
I have generated a secret key in binary format stored in a file, how can i input that file for NIST to run on same .
specifically I need to know how can i provide my secret key in the statted file.

**Comment by stamfest** [comment]
Assuming you are on Linux running the tests on some block of data should be as simple as running

`./rndtest Assess --infile <FILE_WITH_RANDOM_BYTES> -l<number-of-random-bits-to-test-per-iteration> `

Where <FILE_WITH_RANDOM_BYTES> contains random bytes (the default data format is binary) and <number-of-random-bits-to-test-per-iteration> is the number of random bits to use for each iteration of tests. The Assess tool effectively sequentially reads blocks of  <number-of-random-bits-to-test-per-iteration> bits from the file and runs the test suite on it. 

But your problem seems to be how to produce <FILE_WITH_RANDOM_BYTES>. This depends on the tools you are using. 

If you are using /dev/urandom to create eg. 256 bit secret keys using something like

`dd if=/dev/urandom of=/tmp/secretkey bs=32 count=1`

where the blocksize is 32 because 32bytes * 8bits/bytes = 256bits, you can then use 

`./rndtest Assess --infile /tmp/secretkey -l 256`

However, this might not give you the insights into how good the random number source is that you may be looking for, because for this you would need a large set of secret key to check their distribution. Eg. to check the distribution of 4096 different keys you might just create the concatenation of 4096 256 bit random data blocks using 

`dd if=/dev/urandom of=/tmp/secretkeys bs=32 count=4096`

and run 

` ./rndtest Assess --in /tmp/secretkeys -l 256 --progress`

You could use the `-n` parameter to limit the number of iterations. And you could use this to directly test the random number source using e.g. 

` ./rndtest Assess --in /dev/urandom -l 256 -n 4096 --progress`
